/**
 * `pnpm fixtures` — capture a real match transcript for the iOS tests to decode.
 *
 * The generated Swift models are only as good as their agreement with what the server
 * actually puts on the wire, and a hand-written Swift fixture only proves that the models
 * agree with whatever the person writing them assumed. So this drives a real `Room` through a
 * whole match and records every message one player received, byte for byte.
 *
 * The transcript is committed. If the protocol changes and this is not regenerated, the Swift
 * test that decodes it fails — which is the point.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { bidContextOf, legalBidsIn, makeRng, type PlayerId } from '@liars-dice/engine';
import type { ServerMessage } from '@liars-dice/protocol';
import type { Clock, TimerHandle } from '../src/clock.ts';
import { createLogger } from '../src/logger.ts';
import { Room, type SeatSpec } from '../src/room.ts';

const SEED = 20260914;
const SEATS: readonly SeatSpec[] = ['p1', 'p2', 'p3', 'p4'].map((playerId) => ({
  playerId,
  kind: 'human',
}));
/** The seat whose perspective is recorded. Its own dice appear; nobody else's do. */
const SUBJECT: PlayerId = 'p1';

const TIMINGS = { turnMs: 30_000, reconnectGraceMs: 45_000, revealMs: 3_500, botThinkMs: 700 };

/** A hand-cranked clock, so the transcript is identical every time it is regenerated. */
function scriptedClock(): Clock & { advance: (ms: number) => void } {
  let current = 1_700_000_000_000;
  let nextId = 1;
  const timers = new Map<number, { at: number; fn: () => void }>();
  return {
    now: () => current,
    setTimeout(fn, ms) {
      const id = nextId++;
      timers.set(id, { at: current + ms, fn });
      return { id };
    },
    clearTimeout(handle: TimerHandle | null) {
      if (handle !== null) timers.delete(handle.id);
    },
    advance(ms) {
      const target = current + ms;
      for (;;) {
        let dueId: number | null = null;
        let dueAt = Number.POSITIVE_INFINITY;
        for (const [id, timer] of timers) {
          if (timer.at <= target && timer.at < dueAt) {
            dueId = id;
            dueAt = timer.at;
          }
        }
        if (dueId === null) break;
        const timer = timers.get(dueId);
        timers.delete(dueId);
        if (timer === undefined) continue;
        current = timer.at;
        timer.fn();
      }
      current = target;
    },
  };
}

const clock = scriptedClock();
const captured: ServerMessage[] = [];
const decisions = makeRng(SEED ^ 0x5eed);

const room = Room.open({
  matchId: 'fixture-match',
  seats: SEATS,
  timings: TIMINGS,
  clock,
  rng: makeRng(SEED),
  log: createLogger('silent'),
  send: (playerId, message) => {
    if (playerId === SUBJECT) captured.push(message);
  },
});
if (typeof room === 'string') throw new Error(`could not open the room: ${room}`);

/** A legal move for whoever is on turn, chosen deterministically. */
const play = (): boolean => {
  const state = room.debugState;
  if (state.phase.kind !== 'bidding') return false;
  const playerId = state.phase.turnId;
  const options = legalBidsIn(bidContextOf(state));
  const mustBid = state.round.bids.length === 0; // R-06
  if (options.length === 0 || (!mustBid && decisions() < 0.28)) {
    return room.submit(playerId, { type: 'dudo' }) === null;
  }
  const index = Math.min(
    Math.floor(decisions() ** 3 * Math.min(options.length, 8)),
    options.length - 1,
  );
  const bid = options[index];
  if (bid === undefined) return room.submit(playerId, { type: 'dudo' }) === null;
  return room.submit(playerId, { type: 'bid', bid }) === null;
};

// A drop and a return early on, so the transcript exercises the connection events too
// (R-18) rather than only the happy path.
let dropped = false;
for (let step = 0; step < 10_000 && room.currentStatus === 'active'; step += 1) {
  if (room.debugState.phase.kind === 'reveal') {
    clock.advance(TIMINGS.revealMs);
    continue;
  }
  if (!dropped && room.debugState.round.index === 1) {
    dropped = true;
    room.onDisconnected('p2');
    clock.advance(1_000);
    room.onConnected('p2');
    room.resume('p2', 0);
    continue;
  }
  if (!play()) break;
}

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..', '..', '..');
const target = join(repoRoot, 'clients', 'ios', 'Tests', 'Fixtures', 'transcript.json');

const eventTypes = [
  ...new Set(
    captured.flatMap((message) =>
      message.type === 'state' ? message.events.map((event) => event.type) : [],
    ),
  ),
].sort();

const { phase } = room.debugState;
await mkdir(dirname(target), { recursive: true });
await writeFile(
  target,
  `${JSON.stringify(
    {
      note: 'Generated by `pnpm fixtures` from a real Room. Do not hand-edit; regenerate.',
      seed: SEED,
      playerId: SUBJECT,
      winnerId: phase.kind === 'ended' ? phase.winnerId : null,
      messages: captured,
    },
    null,
    2,
  )}\n`,
  'utf8',
);

process.stdout.write(
  `fixtures: ${String(captured.length)} messages, ${String(room.debugState.round.index + 1)} rounds, ` +
    `status ${room.currentStatus}\n  events: ${eventTypes.join(', ')}\n  -> ${target.replace(`${repoRoot}/`, '')}\n`,
);
